# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0002_powermeter_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='powermeter',
            name='current_value',
            field=models.DecimalField(decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='powermeter',
            name='current_value_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
