# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('back_end', '0002_powermeter_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSMRPowerMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('consumed-electricity-day', 'consumed-electricity-day'), ('consumed-electricity-night', 'consumed-electricity-night'), ('produced-electricity-day', 'produced-electricity-day'), ('produced-electricity-night', 'produced-electricity-night'), ('consumed-gas', 'consumed-gas')], max_length=50)),
                ('power_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.PowerMeter')),
            ],
        ),
    ]
