# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    DSMRPowerMeter = apps.get_model('dsmr', 'DSMRPowerMeter')
    DSMRPowerMeter.objects.filter(type='produced-electricity-day').update(
        type='consumed-electricity-1')
    DSMRPowerMeter.objects.filter(type='produced-electricity-night').update(
        type='consumed-electricity-2')
    DSMRPowerMeter.objects.filter(type='produced-electricity-day').update(
        type='produced-electricity-1')
    DSMRPowerMeter.objects.filter(type='produced-electricity-night').update(
        type='produced-electricity-2')


def backwards(apps, schema_editor):
    DSMRPowerMeter = apps.get_model('dsmr', 'DSMRPowerMeter')
    DSMRPowerMeter.objects.filter(type='consumed-electricity-1').update(
        type='produced-electricity-day')
    DSMRPowerMeter.objects.filter(type='consumed-electricity-2').update(
        type='produced-electricity-night')
    DSMRPowerMeter.objects.filter(type='produced-electricity-1').update(
        type='produced-electricity-day')
    DSMRPowerMeter.objects.filter(type='produced-electricity-2').update(
        type='produced-electricity-night')


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsmrpowermeter',
            name='type',
            field=models.CharField(choices=[
                (b'consumed-electricity-1', 'Consumed Electricity Night'),
                (b'consumed-electricity-2', 'Consumed Electricity Day'),
                (b'produced-electricity-1', 'Produced Electricity Night'),
                (b'produced-electricity-2', 'Produced Electricity Day'),
                (b'consumed-gas', 'Consumed Gas')
            ], max_length=50),
        ),
        migrations.RunPython(forwards, backwards),
    ]
